version: '2'
services:
  proxy:
    image: identiproxy:0.2
    links:
      - identidock
    ports:
      - "80:80"

  identidock:
    image: pasquinis/identidock:newest
    environment:
      ENV: PROD
    links:
    - dnmonster
    - redis

  dnmonster:
    image: amouat/dnmonster:1.0

  redis:
    image: redis:3.0

  logspout:
    image: amouat/logspout-logstash
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "8000:80"
    links:
      - logstash
    command: logstash://logstash:5000

  logstash:
    image: logstash:1.5
    volumes:
      - ./logstash.conf:/etc/logstash.conf
    environment:
      LOGSPOUT: ignore
    command: -f /etc/logstash.conf

  elasticsearch:
    image: elasticsearch:1.7
    environment:
      LOGSPOUT: ignore

  kibana:
    image: kibana:4.1
    environment:
      LOGSPOUT: ignore
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - elasticsearch
    ports:
      - "5601:5601"
